# Site settings
title: keutoi
email: k3ut0i@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hacks and Procs that make my life more interesting.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://k3ut0i.github.io" # the base hostname & protocol for your site
github_username:  k3ut0i

# Build settings
markdown: redcarpet
extensions: [fenced_code_blocks]
